name: UI Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15
      - name:  Install Google Chrome 
        run: |
            chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh 
      - name: Run Tests with Maven
        run: |
          mvn -q install
          mvn clean
          mvn test
